name: Deploy To Production

concurrency: production

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Pest Tests and Upload Coverage]
    branches:
      - main
    types:
      - completed
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.filter.outputs.code_changed }}
      docs_changed: ${{ steps.filter.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          code_changed:
            - '**/*.php'
            - '**/*.vue'
            - '**/*.js'
            - '**/*.ts'
            - '**/*.tsx'
            - '**/*.css'
            - '**/*.scss'
          docs_changed:
            - 'docs/**'
            - '**/*.md'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.code_changed == 'true' || needs.changes.outputs.docs_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run' }}
    # Use 2024 Ubuntu, because of newer node version
    runs-on: ubuntu-24.04
    environment: Production
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install ssh keys
        # Check this thread to understand why it's needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
      - name: install composer deps
        if: ${{ needs.changes.outputs.code_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run' }}
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-dev
          tar -czf vendor.tar.gz vendor
      - name: install and build npm deps
        if: ${{ needs.changes.outputs.code_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          npm ci
          # TODO: Possible to maybe use this: https://import-meta-env.org/guide/getting-started/introduction.html#guide
          VITE_POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }} VITE_ARCHYVAS_PASSWORD=${{ secrets.ARCHYVAS_PASSWORD }} VITE_ATSTOVAI_PASSWORD=${{ secrets.ATSTOVAI_PASSWORD }} VITE_SHAREPOINT_CLIENT_ID=${{ secrets.SHAREPOINT_CLIENT_ID }} VITE_SHAREPOINT_TENANT_ID=${{ secrets.SHAREPOINT_TENANT_ID }} npm run build 
          tar -czf build.tar.gz public/build
      - name: build docs
        if: ${{ needs.changes.outputs.docs_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run' }}
        run: |
          npm run docs:build
          tar -czf docs.tar.gz -C docs/.vitepress/dist .
      - name: upload and run on server
        # Unpack
        run: |
          # Test connection
          if [ "${{ needs.changes.outputs.code_changed }}" = "true" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "workflow_run" ]; then
            scp build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.SITE_DIR }}/build.tar.gz
            scp vendor.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.SITE_DIR }}/vendor.tar.gz
          fi
          
          if [ "${{ needs.changes.outputs.docs_changed }}" = "true" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "workflow_run" ]; then
            scp docs.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.SITE_DIR }}/docs.tar.gz
          fi
          
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ vars.SITE_DIR }} && git pull && \
          if [ -f build.tar.gz ]; then rm -rf public/build && tar -xzf build.tar.gz && rm build.tar.gz; fi && \
          if [ -f vendor.tar.gz ]; then rm -rf vendor && tar -xzf vendor.tar.gz && rm vendor.tar.gz; fi && \
          if [ -f docs.tar.gz ]; then rm -rf public/docs/* && tar -xzf docs.tar.gz -C public/docs && rm docs.tar.gz; fi"
      - name: after upload
        if: ${{ needs.changes.outputs.code_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run' }}
        run: |
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ vars.SITE_DIR }} && /opt/php83/bin/php /usr/local/bin/composer dump-autoload && /opt/php83/bin/php artisan optimize"
          rm -rf ~/.ssh
