name: PHP Code Quality

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
      - 'dependabot/composer/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.filter.outputs.php }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          php:
            - '**/*.php'

  setup:
    needs: changes
    # Always run setup in pull requests or when there are PHP changes
    if: ${{ github.event_name == 'pull_request' || needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/setup.yml
      
  lint:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: PHP Linting (Pint)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          
      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-assets
          path: ./
          
      # Fix permissions on the vendor directory
      - name: Fix permissions
        run: chmod -R +x vendor/bin
      
      # Set up environment
      - name: Set up environment
        run: |
          cp .env.example .env
          php artisan key:generate --force
      
      - name: "Laravel Pint"
        uses: aglipanci/laravel-pint-action@2.4
        with:
          preset: laravel
          verboseMode: true
          
      # Auto-commit changes for both direct pushes and PRs
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
          
  static-analysis:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: PHP Static Analysis
    steps:
      - uses: actions/checkout@v4
      
      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-assets
          path: ./
          
      # Fix permissions on the vendor directory
      - name: Fix permissions
        run: |
          chmod -R +x vendor/bin
          chmod -R +x vendor/phpstan/phpstan
          
      # Set up environment
      - name: Set up environment
        run: |
          cp .env.example .env
          php artisan key:generate --force
      
      - name: "Running Static Analysis"
        run: |
          vendor/bin/phpstan analyze --no-progress --memory-limit=384M
      
      # Save analysis results as artifact
      - name: Archive analysis report
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-report
          path: |
            ./phpstan-result.json
          retention-days: 1
          if-no-files-found: ignore