name: PHP Code Quality

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
      - 'dependabot/composer/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.filter.outputs.php }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          php:
            - '**/*.php'

  setup:
    needs: changes
    if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/setup.yml
      
  lint:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: PHP Linting
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-assets
          path: ./
          
      # Download app key separately
      - name: Download APP_KEY
        uses: actions/download-artifact@v4
        with:
          name: app-key
          path: ./
          
      # Fix permissions on the vendor directory
      - name: Fix permissions
        run: chmod -R +x vendor/bin
      
      # Set APP_KEY in environment
      - name: Set APP_KEY
        run: |
          APP_KEY=$(grep APP_KEY .env | cut -d '=' -f2)
          echo "APP_KEY=$APP_KEY" >> $GITHUB_ENV
      
      - name: "Laravel Pint"
        uses: aglipanci/laravel-pint-action@2.4
        with:
          preset: laravel
          verboseMode: true
          
      # Only auto-commit when pushing to feature branches, but not on PRs or main branch
      - name: Git Auto Commit
        if: ${{ github.event_name != 'pull_request' && github.ref != 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
          
      # On PRs, create a review with suggestions instead
      - name: Suggest changes on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: Laravel Pint
          fail_on_error: false
          
  static-analysis:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: PHP Static Analysis
    steps:
      - uses: actions/checkout@v4
      
      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-assets
          path: ./
          
      # Download app key separately
      - name: Download APP_KEY
        uses: actions/download-artifact@v4
        with:
          name: app-key
          path: ./
      
      # Fix permissions on the vendor directory
      - name: Fix permissions
        run: |
          chmod -R +x vendor/bin
          chmod -R +x vendor/phpstan/phpstan
          
      # Set APP_KEY in environment
      - name: Set APP_KEY
        run: |
          APP_KEY=$(grep APP_KEY .env | cut -d '=' -f2)
          echo "APP_KEY=$APP_KEY" >> $GITHUB_ENV
      
      - name: "Running Static Analysis"
        run: |
          vendor/bin/phpstan analyze --no-progress --memory-limit=384M
      
      # Save analysis results as artifact
      - name: Archive analysis report
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-report
          path: |
            ./phpstan-result.json
          retention-days: 1
          if-no-files-found: ignore