name: PHP Static Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
    - 'dependabot/npm_and_yarn/*'
    - 'dependabot/composer/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.filter.outputs.php }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          php:
            - '**/*.php'

  setup:
    needs: changes
    if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/setup.yml
      
  phpstan:
    needs: [changes, setup]
    if: ${{ needs.changes.outputs.php == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: PHP Static Analysis
    steps:
      - uses: actions/checkout@v4
      
      # Download build artifacts from setup
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-assets
          path: ./
      
      - name: "Running Static Analysis"
        run: |
          vendor/phpstan/phpstan/phpstan --no-progress --memory-limit=384M analyze
      
      # Save analysis results as artifact
      - name: Archive analysis report
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-report
          path: |
            ./phpstan-result.json
          retention-days: 1
          if-no-files-found: ignore
