name: Common Setup

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '8.3'
      include-coverage:
        required: false
        type: boolean
        default: false
    outputs:
      cache-hit-composer:
        description: "Whether composer cache was hit"
        value: ${{ jobs.setup.outputs.cache-hit-composer }}
      cache-hit-npm:
        description: "Whether npm cache was hit"
        value: ${{ jobs.setup.outputs.cache-hit-npm }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit-composer: ${{ steps.cache-composer.outputs.cache-hit }}
      cache-hit-npm: ${{ steps.cache-npm.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      
      # PHP setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          coverage: ${{ inputs.include-coverage && 'xdebug' || 'none' }}
          
      # Cache Composer dependencies
      - name: Get Composer cache directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
          
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Generate key
        run: php artisan key:generate
        
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        
      # Cache NPM dependencies
      - name: Cache NPM dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
          
      - name: NPM Install
        run: npm ci
        
      # Build and save artifacts
      - name: NPM Build
        run: npm run build
        
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: |
            public/build
            vendor
          retention-days: 1