name: Common Setup

on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '8.3'
      include-coverage:
        required: false
        type: boolean
        default: false
      node-version:
        required: false
        type: string
        default: '20'
    outputs:
      cache-hit-composer:
        description: "Whether composer cache was hit"
        value: ${{ jobs.setup.outputs.cache-hit-composer }}
      cache-hit-npm:
        description: "Whether npm cache was hit"
        value: ${{ jobs.setup.outputs.cache-hit-npm }}
      cache-hit-build:
        description: "Whether build artifact cache was hit"
        value: ${{ jobs.setup.outputs.cache-hit-build }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-hit-composer: ${{ steps.cache-composer.outputs.cache-hit }}
      cache-hit-npm: ${{ steps.cache-npm.outputs.cache-hit }}
      cache-hit-build: ${{ steps.cache-build.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      # Try to restore build artifact cache first
      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            public/build
            vendor
          key: ${{ runner.os }}-build-${{ hashFiles('**/composer.lock', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
          
      # Skip PHP/Node setup if build cache was hit
      - name: Skip full setup
        id: skip-setup
        if: steps.cache-build.outputs.cache-hit == 'true'
        run: echo "Skipping full setup - using cached artifacts"
          
      # PHP setup - only if build cache missed
      - name: Setup PHP
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          coverage: ${{ inputs.include-coverage && 'xdebug' || 'none' }}
          
      # Cache Composer dependencies - only if build cache missed
      - name: Get Composer cache directory
        if: steps.cache-build.outputs.cache-hit != 'true'
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Cache Composer dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        id: cache-composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
          
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        
      - name: Install Composer Dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Generate key
        run: php artisan key:generate --force
        
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        
      # Cache NPM dependencies - only if build cache missed
      - name: Cache NPM dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
          
      - name: NPM Install
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm ci
        
      # Build only if not cached
      - name: NPM Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm run build
        
      # Status check to ensure workflow completes successfully
      - name: Setup Completed
        run: echo "Setup completed successfully"
        
      # Upload build artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: |
            public/build
            vendor
          retention-days: 1